name: Push

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'

jobs:
  build-helm-and-push-helm:
    uses: stakater-tekton-catalog/.github/.github/workflows/push_tekton.yaml@v0.0.4
    name: Build helm and push to registry, create tag
    with:
      HELM_PACKAGE_NAME: stakater-validate-environment
    secrets:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.GHCR_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
      GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
